# Generated by Django 3.2 on 2023-04-25 15:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(default='', max_length=200)),
                ('tokenno', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starpercent', models.IntegerField(default=0)),
                ('createdtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.IntegerField(default=0)),
                ('delike', models.IntegerField(default=0)),
                ('review', models.CharField(default='', max_length=4000)),
                ('colorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.productcolor')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=200)),
                ('phoneno', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=200)),
                ('fname', models.CharField(default='', max_length=200)),
                ('lname', models.CharField(default='', max_length=200)),
                ('gender', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likestatus', models.CharField(default='', max_length=50)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.register')),
                ('productreview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.productreview')),
            ],
        ),
        migrations.AddField(
            model_name='productreview',
            name='customerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.register'),
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default='', max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('shippingcharge', models.IntegerField(default=0)),
                ('totalprice', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=5000)),
                ('bookeddate', models.DateField(default=django.utils.timezone.now)),
                ('deliverydate', models.DateTimeField(default='')),
                ('payment', models.CharField(default='', max_length=200)),
                ('deliverystatus', models.CharField(default='', max_length=200)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.register')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.productsize')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(default='', max_length=2000)),
                ('nearlocation', models.CharField(default='', max_length=2000)),
                ('city', models.CharField(default='', max_length=2000)),
                ('state', models.CharField(default='', max_length=200)),
                ('pincode', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.register')),
            ],
        ),
        migrations.CreateModel(
            name='CartList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=500)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.productsize')),
            ],
        ),
    ]
